# Generated by Django 2.0.5 on 2018-08-01 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SecondMajorApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('registration_no', models.CharField(max_length=12)),
                ('department', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=1000)),
                ('reason_of_study', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SecondMajorPreCourseList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=10)),
                ('is_complete', models.BooleanField(default=False)),
                ('grade', models.CharField(default='F', max_length=2)),
                ('course_credit', models.FloatField()),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admission.SecondMajorApplication')),
            ],
        ),
    ]
