# Generated by Django 2.0.5 on 2018-08-05 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='secondmajorprecourselist',
            name='applicant',
        ),
        migrations.DeleteModel(
            name='SecondMajorApplication',
        ),
        migrations.DeleteModel(
            name='SecondMajorPreCourseList',
        ),
    ]
