# Generated by Django 2.0.5 on 2018-08-05 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admission', '0002_auto_20180805_0627'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecondMajorApplication',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('registration_no', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('department', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=1000)),
                ('courses_taken', models.TextField(help_text='Write in the format : Course Code<space>Course Credit<space>Course titleExample: EEE101 3.0 Electrical Circuits')),
                ('reason_of_study', models.TextField()),
            ],
        ),
    ]
