# Generated by Django 2.0.5 on 2018-08-05 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0003_secondmajorapplication'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SecondMajorApplication',
        ),
    ]
