# Generated by Django 2.0.5 on 2018-08-15 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0005_secondmajorapplication'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecondMajorCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=6)),
                ('course_credit', models.FloatField()),
                ('course_grade', models.CharField(max_length=2)),
                ('registration_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admission.SecondMajorApplication')),
            ],
        ),
    ]
