# Generated by Django 2.0.5 on 2018-08-15 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0006_secondmajorcourse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='secondmajorapplication',
            name='courses_taken',
        ),
        migrations.RemoveField(
            model_name='secondmajorapplication',
            name='incomplete_course',
        ),
        migrations.AlterField(
            model_name='secondmajorcourse',
            name='course_grade',
            field=models.CharField(default='F', max_length=2),
        ),
    ]
