# Generated by Django 2.0.5 on 2018-08-15 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0007_auto_20180815_1128'),
    ]

    operations = [
        migrations.RenameField(
            model_name='secondmajorcourse',
            old_name='registration_no',
            new_name='registration',
        ),
    ]
