# Generated by Django 2.0.5 on 2018-09-10 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0008_auto_20180815_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secondmajorapplication',
            name='registration_no',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
