# Generated by Django 2.0.5 on 2018-05-27 03:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('date_published', models.DateField(auto_now_add=True)),
                ('upload', models.FileField(upload_to='notices/%Y/%m/%d/')),
            ],
        ),
        migrations.CreateModel(
            name='ProgramCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='notice',
            name='program_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='announcement.ProgramCategory'),
        ),
    ]
