# Generated by Django 2.0.5 on 2018-08-15 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='details',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='honorboard',
            name='details',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='news',
            name='details',
            field=models.TextField(),
        ),
    ]
