# Generated by Django 2.0.5 on 2018-05-26 23:10

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_details', ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
        ),
    ]
