# Generated by Django 2.0.5 on 2018-05-27 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20180526_2313'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About',
        ),
    ]
