# Generated by Django 2.0.5 on 2018-07-28 03:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('published_year', models.CharField(max_length=10)),
                ('link', models.URLField(blank=True, null=True)),
                ('where_published', models.CharField(max_length=500)),
                ('cited_by', models.IntegerField()),
                ('author_faculty', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='people.Faculty')),
                ('author_student', models.ManyToManyField(related_name='students', to='people.Student')),
            ],
        ),
        migrations.CreateModel(
            name='PublicationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ResearchGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date_established', models.DateField()),
                ('office', models.CharField(blank=True, max_length=500, null=True)),
                ('about', models.TextField(blank=True, null=True)),
                ('rules', models.TextField(blank=True, null=True)),
                ('site_link', models.URLField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact', models.CharField(blank=True, max_length=200, null=True)),
                ('research_area', models.ManyToManyField(related_name='research_group', to='people.ResearchArea')),
            ],
        ),
        migrations.CreateModel(
            name='ResearchGroupFaculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=200)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.Faculty')),
                ('research_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='research.ResearchGroup')),
            ],
            options={
                'verbose_name_plural': 'research group faculties',
            },
        ),
        migrations.CreateModel(
            name='ResearchGroupNotice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('date_published', models.DateTimeField(auto_now_add=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('upload', models.FileField(blank=True, null=True, upload_to='research/notices/')),
                ('research_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='research.ResearchGroup')),
            ],
        ),
        migrations.CreateModel(
            name='ResearchGroupProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('details', models.TextField(blank=True, null=True)),
                ('is_funded', models.BooleanField()),
                ('amount', models.FloatField(blank=True, null=True)),
                ('date_range', models.CharField(max_length=200)),
                ('research_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='research.ResearchGroup')),
            ],
        ),
        migrations.CreateModel(
            name='ResearchGroupResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('quantity', models.IntegerField()),
                ('purpose', models.TextField(blank=True, null=True)),
                ('research_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='research.ResearchGroup')),
            ],
        ),
        migrations.CreateModel(
            name='ResearchGroupStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('research_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='research.ResearchGroup')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.Student')),
            ],
        ),
        migrations.AddField(
            model_name='publication',
            name='publication_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='research.PublicationType'),
        ),
        migrations.AddField(
            model_name='publication',
            name='research_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='research.ResearchGroup'),
        ),
    ]
