# Generated by Django 2.0.5 on 2018-06-21 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
        ('research', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='author_student',
        ),
        migrations.AddField(
            model_name='publication',
            name='author_student',
            field=models.ManyToManyField(related_name='students', to='people.Student'),
        ),
    ]
