# Generated by Django 2.0.5 on 2018-08-11 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='author_student',
            field=models.ManyToManyField(blank=True, null=True, related_name='students', to='people.Student'),
        ),
    ]
