# Generated by Django 2.0.5 on 2018-08-11 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0003_auto_20180811_0827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='publication_type',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='research.PublicationType'),
        ),
    ]
