# Generated by Django 2.0.5 on 2018-08-13 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0005_auto_20180811_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='authors',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
