# Generated by Django 2.0.5 on 2018-06-21 04:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('details', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='awards/images/')),
            ],
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=100)),
                ('institution', models.CharField(max_length=200)),
                ('passing_year', models.IntegerField()),
                ('specialization', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience_type', models.CharField(choices=[('academic', 'Academic'), ('technical', 'Technical')], max_length=20)),
                ('organization', models.CharField(max_length=200)),
                ('designation', models.CharField(max_length=200)),
                ('time_duration', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('designation', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='people/images/')),
                ('office', models.CharField(max_length=200)),
                ('contact', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('status', models.CharField(choices=[('in_service', 'In service'), ('on_leave', 'On leave'), ('ex', 'Ex Faculty')], max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ResearchArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ResearchStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.Faculty')),
                ('research_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.ResearchArea')),
            ],
        ),
        migrations.CreateModel(
            name='SocialProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField()),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.Faculty')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('designation', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='people/images/')),
                ('office', models.CharField(max_length=200)),
                ('contact', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('status', models.CharField(choices=[('in_service', 'In service'), ('ex', 'Ex Staff')], max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('registration_no', models.CharField(max_length=12)),
                ('status', models.CharField(choices=[('current', 'Current'), ('allumni', 'Allumni')], max_length=20)),
                ('session', models.CharField(max_length=10)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.Batch')),
            ],
        ),
        migrations.AddField(
            model_name='researchstudent',
            name='student_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.Student'),
        ),
        migrations.AddField(
            model_name='faculty',
            name='research_interest',
            field=models.ManyToManyField(related_name='faculty', to='people.ResearchArea'),
        ),
        migrations.AddField(
            model_name='experience',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.Faculty'),
        ),
        migrations.AddField(
            model_name='education',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.Faculty'),
        ),
    ]
