# Generated by Django 2.0.5 on 2018-08-05 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0002_remove_class_batch'),
        ('people', '0002_auto_20180805_0627'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='batch',
        ),
        migrations.DeleteModel(
            name='Batch',
        ),
    ]
