# Generated by Django 2.0.5 on 2018-08-05 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_auto_20180805_1313'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_year', models.IntegerField()),
                ('syllabus', models.FileField(blank=True, null=True, upload_to='syllabus/')),
            ],
            options={
                'verbose_name_plural': 'batches',
            },
        ),
        migrations.AddField(
            model_name='student',
            name='batch',
            field=models.ForeignKey(default=1991, on_delete=django.db.models.deletion.CASCADE, to='people.Batch'),
            preserve_default=False,
        ),
    ]
