# Generated by Django 2.0.5 on 2018-08-11 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0005_faculty_personal_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='google_scholars_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
