# Generated by Django 2.0.5 on 2018-09-10 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0006_faculty_google_scholars_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='about',
            field=models.CharField(blank=True, default='Hi. A am a proud faculty of SUST CSE.', max_length=2000, null=True),
        ),
    ]
