# Generated by Django 2.0.5 on 2018-09-15 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0007_faculty_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='order_number',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='experience',
            name='order_number',
            field=models.IntegerField(default=1),
        ),
    ]
