# Generated by Django 2.0.5 on 2018-05-26 06:01

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_name', models.CharField(max_length=100)),
                ('curriculum_details', ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
        ),
    ]
