# Generated by Django 2.0.5 on 2018-07-28 03:38

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_current', models.BooleanField(default=False)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.Batch')),
            ],
            options={
                'verbose_name_plural': 'classes',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_type', models.CharField(choices=[('major', 'Major'), ('nonmajor', 'Non-Major'), ('elective', 'Elective')], max_length=20)),
                ('course_code', models.CharField(max_length=20)),
                ('course_title', models.CharField(max_length=100)),
                ('course_details', models.TextField()),
                ('course_credit', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_name', models.CharField(max_length=100)),
                ('details', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_semester', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='program_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='curriculum.Program'),
        ),
        migrations.AddField(
            model_name='course',
            name='year_semester',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='curriculum.Semester'),
        ),
        migrations.AddField(
            model_name='class',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculum.Course'),
        ),
        migrations.AddField(
            model_name='class',
            name='course_teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.Faculty'),
        ),
        migrations.AddField(
            model_name='class',
            name='year_semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculum.Semester'),
        ),
    ]
