# Generated by Django 2.0.5 on 2018-08-05 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='batch',
        ),
    ]
