# Generated by Django 2.0.5 on 2018-06-21 04:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
        ('curriculum', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_current', models.BooleanField(default=False)),
                ('course_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.Faculty')),
                ('course_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculum.Course')),
                ('year_semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculum.Semester')),
            ],
        ),
    ]
