# Generated by Django 2.0.5 on 2018-06-21 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0002_class'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='course_teacher',
        ),
        migrations.RemoveField(
            model_name='class',
            name='course_title',
        ),
        migrations.RemoveField(
            model_name='class',
            name='year_semester',
        ),
        migrations.DeleteModel(
            name='Class',
        ),
    ]
