# Generated by Django 2.0.5 on 2018-08-05 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0004_auto_20180805_1319'),
        ('curriculum', '0002_remove_class_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='batch',
            field=models.ForeignKey(default='1991', on_delete=django.db.models.deletion.CASCADE, to='people.Batch'),
        ),
    ]
