# Generated by Django 2.0.5 on 2018-08-12 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0003_class_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='running',
            field=models.BooleanField(default=False),
        ),
    ]
