# Generated by Django 2.0.5 on 2018-09-12 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0004_semester_running'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_form', models.FileField(blank=True, null=True, upload_to='admission_form/')),
                ('program', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='curriculum.Program')),
            ],
        ),
    ]
